# This is only for development environment
version: '3.1'
services:
    web:
        image: gogs/gogs
        depends_on:
            - database
        volumes:
            - /var/gogs:/data
        ports:
            - "3000:3000"

    database:
        image: mysql:latest
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: gogs
        volumes:
            - ./.persistence:/var/lib/mysql
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
